serial:
  port: /dev/ttyF9P # or COMx on Windows
  baud: 115200
  timeout: 1.0

server:
  host: 127.0.0.1
  port: 5000

map:
  initial_zoom: 2
  max_zoom: 20
  first_fix_zoom:
    hacc_over_50: 16
    hacc_over_15: 17
    hacc_over_5: 18
    default: 19
  path_max_points: 2000
  update_interval_ms: 250

ntrip:
  enabled: true
  host: 0.0.0.0  # put your NTRIP caster host here
  port: 2101
  mountpoint: YOUR_MOUNTPOINT  # put your NTRIP mountpoint here
  username: YOUR_USERNAME  # put your NTRIP username here
  password: YOUR_PASSWORD  # put your NTRIP password here
  tls: false
  timeout_s: 10.0
  reconnect_s: 5.0
  gga_interval_s: 10.0